### ISSUE TITLE
Создать рест эндпоинт - заглушку

### ISSUE THREAD

**Issue by r331** [faasj/deployer#1]
Сервис gateway будет вызывать данный эндпоинт для получения данных по запущенной функции и ее старту.
Методы должны быть следующие
void uninstallFunction(UUID function);
List<FunctionDeploymentDto> getDeployedFunctions();
void deployFunction(FunctionDefinition funDeployRequest);
String getLogs(String name, LocalDateTime since);

Продумать что передавать в дто

**Comment by i7bro** [comment]
Кроме imageName, envVar не могу представить, что еще нужно для деплоя. Возможно, tags, progectId...

**Comment by r331** [comment]
Ещё ресурсы и аннотации.

**Comment by i7bro** [comment]
Точно, ресурсы же при билде не потребуются, только для рантайма...
